//
//  API.h
//  Banana
//
//  Created by 朱标 on 2018/11/19.
//

#import <Foundation/Foundation.h>

NS_ASSUME_NONNULL_BEGIN

@interface API : NSObject

@end

NS_ASSUME_NONNULL_END

FOUNDATION_EXPORT NSString *const API_NAME;

FOUNDATION_EXPORT NSString *const MEMBER_LOGIN;

FOUNDATION_EXPORT NSString *const MEMBER_REGISTER;

FOUNDATION_EXPORT NSString *const SYS_SENDNOTE;

FOUNDATION_EXPORT NSString *const MEMBER_SELECTINFORMATION;

FOUNDATION_EXPORT NSString *const MEMBER_LOGOUT;

FOUNDATION_EXPORT NSString *const MEMEBER_CHANGEPWD;

FOUNDATION_EXPORT NSString *const SYS_IDEA;

FOUNDATION_EXPORT NSString *const MEMBER_CHANGEBIND;

FOUNDATION_EXPORT NSString *const SYS_VALIDATECHECKCODE;

FOUNDATION_EXPORT NSString *const MEMBER_CHANGEMSG;

FOUNDATION_EXPORT NSString *const MEMBER_CHANGEHEADFILE;



FOUNDATION_EXPORT NSString *const MEMEBER_startShow;

FOUNDATION_EXPORT NSString *const MEMEBER_HOMEDATA;


